# Generated by Django 6.0.2 on 2026-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('black', 'Black')], max_length=50)),
                ('water_requirement', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('monsoon', 'Monsoon'), ('winter', 'Winter')], max_length=20)),
                ('budget_range', models.IntegerField()),
                ('advantages', models.TextField()),
                ('cultivation_process', models.TextField()),
                ('yield_tips', models.TextField()),
            ],
        ),
    ]
